---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-as-code-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec: 
    params:
    - name: echo-value
      description: The value to echo out
      default: code
    tasks:
      - name: fetch
        taskSpec:
          params:
          - name: echo-value-for-task
            description: The value to echo out
            default: this is not the param you're looking for
          steps:
            - name: echo
              image: ubuntu
              command:
                - echo
              args:
                - "$(inputs.params.echo-value-for-task)"
        params:
          - name: echo-value-for-task
            value: "fetching $(params.echo-value)"
